### ISSUE TITLE
TypeError: undefined のメソッド「replace」を呼び出せません。（行 209、ファイル「」）

### ISSUE THREAD

**Issue by hotuta** [motemen/gas-slack-log-spreadsheet#1]
早速活用させて頂きました。
物凄く助かります!
ところで、実行した所、下記のエラーメッセージが出ました。
TypeError: undefined のメソッド「replace」を呼び出せません。（行 209、ファイル「」）
スプレッドシートの中身を確認した所、どうやらTwitterのBotの内容が上手く取得できていないみたいです。

**Comment by motemen** [comment]
ありがとうございます、修正しました。

**Comment by hotuta** [comment]
こちらこそどうもありがとうございます。問題なく動作するようになりました!
